// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApO6C5dCX_o-wcFngjoTN9pu0sVRCdBDI',
    appId: '1:90873001029:web:d9545fd6cfa5b964031f2c',
    messagingSenderId: '90873001029',
    projectId: 'fir-flutter-codelab-938a2',
    authDomain: 'fir-flutter-codelab-938a2.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-938a2.firebasestorage.app',
    measurementId: 'G-90KCB6DQ2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsFfZUh9jfTZi6UX8mpNpHjXHQJJnA9Z0',
    appId: '1:90873001029:android:e6f88d78785f98cc031f2c',
    messagingSenderId: '90873001029',
    projectId: 'fir-flutter-codelab-938a2',
    storageBucket: 'fir-flutter-codelab-938a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFg8ZjMzZ-mEXL7Oo0vz7PYI6psXCzZ1I',
    appId: '1:90873001029:ios:a0e271c1644c4f1d031f2c',
    messagingSenderId: '90873001029',
    projectId: 'fir-flutter-codelab-938a2',
    storageBucket: 'fir-flutter-codelab-938a2.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFg8ZjMzZ-mEXL7Oo0vz7PYI6psXCzZ1I',
    appId: '1:90873001029:ios:a0e271c1644c4f1d031f2c',
    messagingSenderId: '90873001029',
    projectId: 'fir-flutter-codelab-938a2',
    storageBucket: 'fir-flutter-codelab-938a2.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
